### PR TITLE
Feature/rui icon

### PR DESCRIPTION
**Pull request by ricominten**
Added rui-icon

screencapture-localhost-8000-docs-components-rui-icon-2019-07-30-15_40_06

### CODE REVIEW

**Comment by ricominten** [comment]
Open to comments on what's best to do with this as a component.

Hover states can realistically be removed as the hover would be detected on the parent company and passed down.
eg.
`button rui-icon { colours }`
`button:hover rui-icon { hover-colours }`

Also need to add IE11 support.

**Comment by ricominten** [comment]
relates to #20

**Comment by jennasalau** [comment]
Im not so sure rui-icon should have a hover style..

Given the following example

```
<a href="/home"
     <rui-icon src="./home-icon.svg" />
     <span>Visit home page</span>
</a>
```

I would expect to write the following css

```
a {
   --rui-icon__color: black;
}

a:hover {
   --rui-icon__color: purple;
}
```

I'm just not sure when we would want the icon itself to have a hover state in isolation, it will usually be within an a tag or button

**Comment by ricominten** [comment]
> Im not so sure rui-icon should have a hover style..
> 
> ...
> 
> I'm just not sure when we would want the icon itself to have a hover state in isolation, it will usually be within an a tag or button

Agree, it's something I mentioned above as well. Will update and remove it

**Comment by ricominten** [comment]
@jennasalau removed the hover state from the icon

**Pull request merged**
